Dark Mode toggle
future-standard/scorer-ui-kit pull request #269
Opened 2022-02-01 07:25 UTC by JoshLipps

2022-02-01 10:43 UTC, isacoder requested changes
Hello @fti-dshelke  for taking this tasks in this confusing theming process @-@,
I started this review without description, @fti-dshelke if you could provide I would be helpful.

This update has no story in storybook, usually I wouldn't mind but this made very hard to review and by trying to update storybook to review discovered the missing parts.
TopBar is not passing the props to UserMenu related for the theming, neither text nor toggle so the button is not doing anything.

Another not functionality related fix is the color of the text does not look good on black theme.
I imagine the design didn't provide a value, you can use the username theme color for text, I think this will make it look better.

<img width="1237" alt="Screen Shot 2022-02-01 at 19 22 57" src="https://user-images.githubusercontent.com/10409078/151953928-254d4dcb-25dc-4adc-961e-ed83501127e9.png">


<img width="1350" alt="Screen Shot 2022-02-01 at 19 23 07" src="https://user-images.githubusercontent.com/10409078/151953900-42f3bab2-050b-4235-b996-c182f5ab4774.png">

Please add the storybook update.
 Theming toggle can be added as a knob action, look at buttons story it's just a click that shows in the action section.

2022-02-04 05:50 UTC, fti-dshelke commented
> Hello @fti-dshelke for taking this tasks in this confusing theming process @-@, I started this review without description, @fti-dshelke if you could provide I would be helpful.
> 
> This update has no story in storybook, usually I wouldn't mind but this made very hard to review and by trying to update storybook to review discovered the missing parts. TopBar is not passing the props to UserMenu related for the theming, neither text nor toggle so the button is not doing anything.
> 
> Another not functionality related fix is the color of the text does not look good on black theme. I imagine the design didn't provide a value, you can use the username theme color for text, I think this will make it look better.
> 
> <img alt="Screen Shot 2022-02-01 at 19 22 57" width="1237" src="https://user-images.githubusercontent.com/10409078/151953928-254d4dcb-25dc-4adc-961e-ed83501127e9.png">
> 
> <img alt="Screen Shot 2022-02-01 at 19 23 07" width="1350" src="https://user-images.githubusercontent.com/10409078/151953900-42f3bab2-050b-4235-b996-c182f5ab4774.png">
> 
> Please add the storybook update. Theming toggle can be added as a knob action, look at buttons story it's just a click that shows in the action section.

@isacoder Thanks for reviewing.
I will update the remianing tasks

2022-02-08 08:27 UTC, isacoder commented
Hi!

I was able to review the theme change and  get the trigger of the buttons when theme and language 

The only thing I see that needs to be fixed is the color of the text for visibility as requested.
<img width="1328" alt="Screen Shot 2022-02-08 at 17 25 03" src="https://user-images.githubusercontent.com/10409078/152947333-4fb54163-47df-4d11-a9a1-49e83a974d87.png">

2022-02-08 09:34 UTC, fti-dshelke commented
> Hi!
> 
> I was able to review the theme change and get the trigger of the buttons when theme and language
> 
> The only thing I see that needs to be fixed is the color of the text for visibility as requested. <img alt="Screen Shot 2022-02-08 at 17 25 03" width="1328" src="https://user-images.githubusercontent.com/10409078/152947333-4fb54163-47df-4d11-a9a1-49e83a974d87.png">

Done

2022-02-08 10:43 UTC, isacoder requested changes
Sorry for this late change request, just realized after thinking how to get the DarkMode Icon to see it.

perhaps instead of just the action for the story, might be better to add the state
const [isLightMode, setIsLightMode] = useState(true)

const onThemeToggle = () => {
   setIsLightMode((prev) => !prev)
}

2022-02-08 10:43 UTC, isacoder commented on src/Global/atoms/DrawerBottomMenu.tsx
> +  selectedValue: string,
Hi Dipak, 
I realized that selectedValue is a string and is only providing the text to be displayed and not the actual value, it does not provide functionality.

Maybe in this case should be more like a subtitle of the DrawerBottomMenu

2022-02-15 08:54 UTC, isacoder requested changes
Hello!

I have look at the changes thanks for updating the naming of the variables.
I saw you took the pain of  trying to update the light mode/dark mode text :( but is not showing.
 
![Screen Shot 2022-02-15 at 17 47 05](https://user-images.githubusercontent.com/10409078/154025967-62e3b70c-7dd0-4d40-b82d-5bc33500c22d.png)


I think you need to do it directly in the component not with the text knob.
please update it there.

Also since you have updated before the Global UI story, please update this too there to keep it consistent.

2022-02-15 09:12 UTC, fti-dshelke commented
> I think you need to do it directly in the component not with the text knob. please update it there.

But we have prop (**selectedThemeText**) to update the text.

2022-02-15 09:26 UTC, isacoder commented
> > I think you need to do it directly in the component not with the text knob. please update it there.
> 
> But we have prop (**selectedThemeText**) to update the text.

I meant the Storybook component
<img width="964" alt="Screen Shot 2022-02-15 at 18 20 04" src="https://user-images.githubusercontent.com/10409078/154031397-05f20659-6de7-41a0-af92-dc17c98fca70.png">

2022-02-15 12:02 UTC, fti-dshelke commented
Updated the storybook for global UI
![image](https://user-images.githubusercontent.com/67998680/154057081-992be109-7598-4efd-a1ab-010f4ba930de.png)

2022-02-16 08:40 UTC, isacoder approved these changes
Thanks for updating all the changes requested, this branch is ready to merge.

2022-02-16 09:09 UTC, merged