Feature/user drawer enhancement 2
future-standard/scorer-ui-kit pull request #382
Opened 2022-11-01 15:31 UTC by fti-pfarne

###Description
This PR has an enhancements in User Drawer (TopBar) to shown additional meta informations like DeviceID, Device Name, Version etc as per application need.
This changes are based on below bugherd issues in Traffic Counter Edge application

- Bugherd Requirements links

[Requirement 1](https://www.bugherd.com/projects/289019/tasks/12)
[Requirement 2](https://www.bugherd.com/projects/289019/tasks/20)

- Design link

[Design](https://app.zeplin.io/project/622084ffc57fbd589f11ef42/screen/6299c853789018ad3a1d6414)

###Considerations on Implementation

Added a prop hasUserDrawerMeta, if it is true then it can show User Drawer Meta information above the Account Information section else not.
Added a prop userDrawerMeta for adding meta information in a array. By using this you can show multiple meta information in drawer.
If there are more than 3 meta object then it will be scrolled.
Added a prop userDrawerFooter to show details in drawer footer like application version.
Added prop onUserDrawerMetaClick for on Click functionality of meta object so if needed application can perform any action on click of this meta.

###Screenshots

2022-11-02 07:07 UTC, fti-bcarpenter requested changes

2022-11-02 07:07 UTC, fti-bcarpenter commented on src/Global/molecules/UserMenu.tsx
> +  max-width: 136px;
Make this conditional if there is a icon then it should be 136px else it should be 161px.
Please verify this on all resolutions.

2022-11-02 07:07 UTC, fti-bcarpenter commented on storybook/src/stories/Global/GlobalUI.stories.tsx
> +        {...{ logoMark, logoText, supportUrl, maxWidth, paddingOverride, notificationsHistory, customDrawer }}
Remove empty space which is at the end of line

2022-11-02 11:15 UTC, fti-bcarpenter approved these changes

2022-11-07 06:12 UTC, fti-skumar commented on src/Global/atoms/UserDrawerMeta.tsx
> +  user-select: all;
I think we do not need `user-select` property to select text, its by default selectable unless we made it un-selectable which happens in this case, where you first made `user-select: none`, then uses this `user-select: all` to select. I think you just need to remove this `user-select: none`.

2022-11-07 06:13 UTC, fti-skumar commented on src/Global/atoms/UserDrawerMeta.tsx
> +  user-select: all;
Please also check and remove here as well.

2022-11-07 06:13 UTC, fti-skumar commented on src/Global/atoms/UserDrawerMeta.tsx
> +  user-select: all;
Please also check and remove here as well.

2022-11-07 06:14 UTC, fti-skumar commented on src/Global/molecules/UserMenu.tsx
> +  user-select: all;
Please remove `user-select: all` as we don't need it.

2022-11-07 06:16 UTC, fti-skumar requested changes
Please also check other functionalities like user-meta-click after that `user-select` change.

2022-11-09 04:29 UTC, fti-skumar commented on src/Global/molecules/UserMenu.tsx
> +                dataObjKey={key}
Thanks for the changes, just one thing please also change this name to something like `userMetaIndex` .

2022-11-09 05:43 UTC, fti-skumar commented
Thanks @fti-pfarne for the updates, LGTM.

2022-11-09 05:44 UTC, fti-skumar approved these changes

2022-11-09 06:20 UTC, fti-bcarpenter approved these changes

2022-11-16 08:49 UTC, atomworks approved these changes
👍

2022-12-19 17:10 UTC, merged