Added "Clear Files" button to Area Upload Manager to reset selected files
future-standard/scorer-ui-kit pull request #407
Opened 2023-04-03 12:43 UTC by fti-rchaniya

**Description**
This PR has following change in the Area Upload Manager component:

- While using this component, if an user wants to set selected files to null by an external triggered event such as close icon or button as shown in below attached screenshot, then the selected files does not reset to null due to the absence of prop which setFiles(null).
![image](https://user-images.githubusercontent.com/118800413/229511496-39f98470-53ca-4d91-b789-b46669d6f7ae.png)

- Due to this, even if user click on close icon, and add files again so the expected behaviour is the selected file's count start from 0 which is not, it starts adding in the array where the previously added files are saved. 
- For more understanding, kindly refer below screencast:
https://www.awesomescreenshot.com/video/16183735?key=219730f4f27ff7f0ec403ed16e3e3611

**Considerations on Implementation**

- To achieve this, earlier we thought to add 1 Boolean state to the component which an user can use as a prop to setFiles(null) as shown in below attached screenshot.
![image](https://user-images.githubusercontent.com/118800413/229512438-ec5f4d9a-e787-4f91-be5f-9535c6a419bd.png)

- Instead of the above solution, we approaches another suggestion given in this [comment](https://github.com/future-standard/scorer-ui-kit/pull/407#pullrequestreview-1377390065).
- As per the above comment, instead of adding prop to trigger external event, we have added a "Clear Files" button in the component itself to clear selected files.
- Also "Clear Files" button will be only visible if the selected files count is more than 0, it is aligned parallelly with the "Select Files"/"Add More Files" button as shown in the below attached screenshot:
![image](https://user-images.githubusercontent.com/118800413/231092150-0b7a8f35-c7f7-4049-bdf6-2fd7873ecb85.png)

Screencast of the final implementation:
https://www.awesomescreenshot.com/video/16402979?key=eaec76b4966083b3e92b269a375fde97

2023-04-04 04:21 UTC, fti-smaske commented on src/Form/organisms/AreaUploadManager.tsx
> +  clearState?: boolean;
Change varaible name to `clearFiles`

2023-04-05 05:27 UTC, fti-skumar approved these changes
LGTM, just change the name as suggested by @fti-smaske

2023-04-10 06:18 UTC, fti-rchaniya commented on src/Form/organisms/AreaUploadManager.tsx
> +  clearState?: boolean;
Done, thanks for the feedback

2023-04-10 06:20 UTC, fti-smaske approved these changes

2023-04-10 07:57 UTC, fti-bcarpenter requested changes

2023-04-10 07:57 UTC, fti-bcarpenter commented on storybook/src/stories/Form/FileManagement/AreaUploadManager.stories.tsx
> +  let clearState = boolean('Clear selected Files', false);
This should be `clearFiles`. Isn't it?

2023-04-10 07:57 UTC, fti-bcarpenter commented on storybook/src/stories/Form/FileManagement/AreaUploadManager.stories.tsx
> +        clearState={clearState}
This should be `clearFiles`. Isn't it?

2023-04-10 09:23 UTC, fti-bcarpenter approved these changes
LGTM

2023-04-10 10:55 UTC, atomworks requested changes
Could we move the button to clear this in to the AreaUploadManager component itself? I think we can just show it all the time as it's useful. 

Just one of the grey buttons, small size and centered in the container would be great.

2023-04-10 12:00 UTC, fti-rchaniya commented
> Could we move the button to clear this in to the AreaUploadManager component itself? I think we can just show it all the time as it's useful.
> 
> Just one of the grey buttons, small size and centered in the container would be great.

Yes, we can. Can you please confirm me the place where we can place that button to clear files

2023-04-11 08:05 UTC, fti-rchaniya commented
> Could we move the button to clear this in to the AreaUploadManager component itself? I think we can just show it all the time as it's useful.
> 
> Just one of the grey buttons, small size and centered in the container would be great.

Thanks for the feedback, suggested changes have been implemented

2023-04-11 11:01 UTC, atomworks approved these changes

2023-04-12 02:51 UTC, merged