ICustomDrawer -> modified interface type of counter to accept string or number
future-standard/scorer-ui-kit pull request #415
Opened 2023-07-26 07:26 UTC by fti-rchaniya

### Description
This PR consist a following change in the ICustomDrawer interface-

1. In TopBar component, when the user showing a count of the notifications there might be possibility that count length gets increase to 4 or more as shown in below attached snap-
![image](https://github.com/future-standard/scorer-ui-kit/assets/118800413/2217cab0-26bc-4330-a08e-b825a4ee9b5c)

2. In order to get rid of such behaviour, we decided that if count exceeds **999** then we can show it as **999+** , as shown in below attached snap-
![image](https://github.com/future-standard/scorer-ui-kit/assets/118800413/14b7dca3-fc2a-4bbf-9748-c5a48c417c69)

3. To achieve above, we need to concatenate a number with **+** sign, which will return a string 
4. But as **counter** in **ICustomDrawer** accepts number only it throws an error
5. Hence, we modified type of **counter** in **ICustomDrawer** as below:
**counter?: number | string**

Kindly go through below BH requirement link in order to get better clarity 

[BH Requirement](https://www.bugherd.com/projects/263632/tasks/325)

2023-07-26 09:07 UTC, fti-skumar approved these changes

2023-07-26 11:25 UTC, fti-bcarpenter approved these changes
LGTM

2023-07-27 03:15 UTC, atomworks requested changes
It would be better to add a new prop called `maxCounter` and have that as a default of `999` and then use some logic internally to set the `+` suffix behaviour.

As an additional request, would we change the background that is behind the number to have a border radius of 4px? At the moment, the intended circle shape doesn't work on longer values as it stretches so a fix bored radius would look cleaner. Thank you.

2023-07-27 09:28 UTC, fti-rchaniya commented
> It would be better to add a new prop called `maxCounter` and have that as a default of `999` and then use some logic internally to set the `+` suffix behaviour.
> 
> As an additional request, would we change the background that is behind the number to have a border radius of 4px? At the moment, the intended circle shape doesn't work on longer values as it stretches so a fix bored radius would look cleaner. Thank you.

Done
Below is the snap for ui change.
![image](https://github.com/future-standard/scorer-ui-kit/assets/118800413/d2e48124-3e82-4581-872d-cb12b536beba)

2023-07-31 04:46 UTC, fti-skumar approved these changes

2023-07-31 06:28 UTC, fti-bcarpenter requested changes

2023-07-31 06:28 UTC, fti-bcarpenter commented on storybook/src/stories/Global/GlobalUI.stories.tsx
> +  // maxCounter: 1000,
Remove this if not needed.

2023-07-31 06:28 UTC, fti-bcarpenter commented on src/Icons/StatusIcon.tsx
> +  border-radius: 4px;
Attach the snapshot with border-radius 4px in this PR.

2023-07-31 09:08 UTC, fti-rchaniya commented on storybook/src/stories/Global/GlobalUI.stories.tsx
> +  // maxCounter: 1000,
Done

2023-07-31 10:29 UTC, fti-bcarpenter approved these changes
LGTM

2023-08-08 09:52 UTC, atomworks approved these changes

2023-08-08 10:00 UTC, merged