Percentage Slider -> Added prop to handle ValueTitle show/hide behaviour
future-standard/scorer-ui-kit pull request #425
Opened 2023-10-09 10:38 UTC by fti-rchaniya

**Description**
This PR has following enhancement in the **PercentageSlider** component:

1. In our current component, we have Value title label showing at the top of the slider bar, as showing in the below attached snapshot.
![image](https://github.com/future-standard/scorer-ui-kit/assets/118800413/bb5b69bc-f35c-4c1e-8a34-9f246b4cc4fd)

2. There is a chances to make it's visibility show/hide based on the Boolean value passed by an user.

3. Hence, I have added a boolean prop named **showValueTitle** which will handle visibility of an element based on the value provided.

4. If true then label will be shown else it will be hidden.

2023-10-10 06:31 UTC, fti-smaske approved these changes

2023-10-16 05:04 UTC, fti-pfarne approved these changes
Looks good

2023-10-17 11:40 UTC, fti-bcarpenter requested changes

2023-10-17 11:40 UTC, fti-bcarpenter commented on storybook/src/stories/Form/Input/PercentageSlider.stories.tsx
> +  const showValueTitle = boolean("Value title visible", false);
"Value title visible" --> "Show Value Title"

2023-10-18 04:28 UTC, fti-rchaniya commented on storybook/src/stories/Form/Input/PercentageSlider.stories.tsx
> +  const showValueTitle = boolean("Value title visible", false);
Done

2023-10-18 05:38 UTC, fti-bcarpenter approved these changes

2023-10-19 03:31 UTC, atomworks requested changes
Looks good. Only small request, can we change `showValueTitle` to just `showValue`? Thanks!

2023-10-19 04:17 UTC, fti-rchaniya commented
> Looks good. Only small request, can we change `showValueTitle` to just `showValue`? Thanks!

Certainly! I've made the necessary changes as requested. Please review the updated version.

2023-10-19 10:56 UTC, atomworks approved these changes

2023-10-19 10:57 UTC, merged