Tag element and list of tags
future-standard/scorer-ui-kit pull request #49
Opened 2021-03-22 12:39 UTC by isacoder

### Request
Tags
[Tags] Add tags UI element to UI kit
[Bugherd#45](https://www.bugherd.com/projects/216308/tasks/45)

[Functionality specifics the tag](https://app.slack.com/docs/T0ALXERMZ/F01R5DCL0DB?origin_team=T0ALXERMZ&origin_channel=DMLC36D7T)

### Implementation
I added the size feature taking it from the icon style.
however I didn't made the padding proportional.
This could be easier with EM's I think.
Since you mention this could be change in the feature didn't put to much time on this.

I read some of the documentation of React Router.
I think the component should be just sent in the link.

Tomorrow I will corroborate this by making the list feature.

### Screenshoots

<img width="503" alt="Screen Shot 2021-03-22 at 21 30 44" src="https://user-images.githubusercontent.com/10409078/111990025-dd869d80-8b55-11eb-9702-e73784646751.png">

2021-04-22 09:08 UTC, atomworks requested changes
Sorry this one has taken so long to give feedback for. 

There's a couple of change requests here when you're able to take a look.

- [ ] We don't need to provide any alternative colors. The default one is great.
- [ ] For the TagLink, when hovering can we use the primary color?
- [ ] Would it be possible to move the link functionality of TagLink in to the main Tag component and conditionally enabled the link behaviour (like enableHover) if a `to` prop is provided?

2021-04-22 09:10 UTC, atomworks commented on storybook/src/stories/Misc/atoms/Tag.stories.tsx
> +const colorOptions = { EmtpyValue: "", Mono: "mono", Dimmed: "dimmed", Subtle: "subtle", Inverse: "inverse", Primary: "primary", Danger : "danger" };
Typo on empty!

2021-04-23 11:54 UTC, isacoder commented on storybook/src/stories/Misc/atoms/Tag.stories.tsx
> +const colorOptions = { EmtpyValue: "", Mono: "mono", Dimmed: "dimmed", Subtle: "subtle", Inverse: "inverse", Primary: "primary", Danger : "danger" };
Removed

2021-04-23 11:58 UTC, isacoder commented
I have updated the basic colors as the design on zeppling.
I realized it wasn't in the PR before.
The colors are not the basic colors of SVG.

I want to confirm that this is correct. Sorry for not asking before.

https://zpl.io/agxkp51
zpl://screen?sid=604edad8c702888f4a043947&pid=5ee9f5a23a30524bf9e5b2a9

2021-04-28 06:03 UTC, atomworks commented
> I have updated the basic colors as the design on zeppling.
> I realized it wasn't in the PR before.
> The colors are not the basic colors of SVG.
> 
> I want to confirm that this is correct. Sorry for not asking before.
> 
> https://zpl.io/agxkp51
> zpl://screen?sid=604edad8c702888f4a043947&pid=5ee9f5a23a30524bf9e5b2a9

Sorry, I totally missed this. Yes, those should be correct.

2021-05-12 03:52 UTC, atomworks approved these changes

2021-05-14 09:02 UTC, merged