Form component refactors
future-standard/scorer-ui-kit pull request #496
Opened 2024-10-15 10:56 UTC by atomworks

## Updates
This PR contains two main changes:
1. Refactor inputs to match designs and use the new CSS variables.
2. Introduced a new blue dot 🔵 next to field labels to signify they are required fields.

This refactors some the common form fields that have had design tweaks and seeks to replace legacy theming with the new CSS variables.

### 1. Input Refactors and Prop Improvements
This is similar to previous refactors. It updates sizes and colors, introducing the usage of new CSS variables and removing the old theme integrations.

`Input`, `InputField`, `TextArea`, `TextAreaField` and `PasswordField` have a new `showFeedback?: boolean` prop which if not set will default to `false`. This is because the feedback messages are no often used in designs however this feature is planned to be iterated, in which case the new feature will use the same props. Even in this instance we want to retain more control over when these are shown.

This also allows us to properly utilise these input states without having the feedback area appear incorrectly.

**Action when updating to this version of the UI Kit:** If your project uses any of the mentioned components and those instances have `feedbackMessage` in use you need to add the `showFeedback={true}` as a prop to once more recreate the previous behaviour.

### 2. Required - Blue Dot 🔵
This pattern has been used on some more recent designs and will begin to appear with more regularity moving forward. It looks like this...
![image](https://github.com/user-attachments/assets/c0b24e3c-251e-4253-a4b1-c0575647d507)

- Label has a blue dot that will show if passed a `required` prop. The various `xxField` components and stories have been updated with this. If any of these appear to be missing, please report it as a bug.
- If a project does not use the blue dot for required fields but required is used as a prop, you can override the CSS variable `--input-required-dot-display` to be `none` instead. This can be done globally or on a component level. See examples for CSS overrides.
- Please note: This `required` field is different to the `required` value in the componets `fieldState` prop. This new `required` prop signifies that the field is required where as the `fieldState='required'` is used when the form has been submitted but the field was left empty.

### Additional Change Notes
- Stories that had backgrounds added and awkward borders as a result have been removed. All stories already used the correct background.

2024-10-23 03:40 UTC, isacoder requested changes
Hello Leonard,

Thank you for the update! The inputs look much brighter now with the new colors. I’ve left a few comments, mainly regarding the layout of the input, which needs a bit of polishing. The PR looks good and once these updates are made it will be ready for approval.

2024-10-23 08:29 UTC, atomworks commented on packages/ui-lib/src/Form/atoms/Label.tsx
> +      /* margin-left: 8px; */
Nope! I've removed it it. Thank you.

2024-10-23 09:59 UTC, atomworks commented on packages/ui-lib/src/theme/variables/Colors.ts
> +    /* --input-default-shadow-color: var(--grey-3); */
They were left there as I was thinking about using these in a later iteration. Ended up going down a bit of a rabbit hole and finishing that thought in the code.

Basically now, I've uncommented those, made the default values transparent and added other box-shadow variables so things can be overriden for different uses in the future. In the current state it should all however appear the same.

2024-10-23 10:01 UTC, atomworks commented on packages/ui-lib/src/Form/atoms/Input.tsx
>          return <Spinner size='medium' styling='primary' />;
As per the previous comment, I've moved the box back where it should be for `Input`. Any other styling should be as it was but any left over issues in this box I think we can leave until we iterate it, as it doesn't really get used.

2024-10-24 05:07 UTC, isacoder approved these changes
All updates looks good, this PR is ready to merge 👍

2024-10-24 05:16 UTC, merged