Datepicker Dot Markers
future-standard/scorer-ui-kit pull request #524
Opened 2024-12-04 06:45 UTC by isacoder

### Description

This is a new Feature request for the Datepicker

`
A new date picker feature where a list of dates or date ranges can be provided which will then place a dot on the date picker to signify, for example, that there is content available to view within that range.
`

 ### Considerations on Implementation
Moved examples data to new data helper file for DatePicker examples.
I decided to add go with the dates array for content.

 ### Reviewing/Testing steps
Test in Storybook

Filters -> Molecules -> DatePicker
<img width="640" alt="Screenshot 2024-12-04 at 15 44 03" src="https://github.com/user-attachments/assets/59d4e245-c575-4ff3-b174-c62b202a0d53">

Filters -> Organism -> FilterBar
<img width="918" alt="Screenshot 2024-12-04 at 15 43 15" src="https://github.com/user-attachments/assets/7fffb8ea-dfcc-4dda-b4d1-721b4d985a22">

2024-12-05 07:29 UTC, atomworks requested changes
Looking great... just three things, from small to big. Depending on your thoughts, the third might not need any work right now.

1. I'd like to revise the dot colors slightly - I'll leave the changes in the code comments.
2. While the dot is in the right place, the number itself needs to go up by 1px.
3. --The date array approach looks great though I'm concerned that it's a little messy to have required in this field again. I know we have it in the date range fields themselves but as I'd like to revise and remove that in the future when we can start to make breaking changes, I'd rather avoid it for now. What are your thoughts?--

Thank you!

2024-12-05 07:29 UTC, atomworks commented on packages/ui-lib/src/Filters/molecules/DatePicker.tsx
> +  background-color: var(--info-10);
Can we update this to `--primary-11` please.

2024-12-05 07:29 UTC, atomworks commented on packages/ui-lib/src/Filters/molecules/DatePicker.tsx
> +    background-color: var(--white-12);`
For `inside` can we make this `--primary-12` please. The other states should remain `--white-12`, thank you.

2024-12-06 06:32 UTC, isacoder commented
I have updated the colors, I will review with @atomworks  points 2 and 3 to understand better these requirements before updating the PR.

<img width="559" alt="Screenshot 2024-12-06 at 15 31 52" src="https://github.com/user-attachments/assets/efb75ee0-b957-48ca-9908-11514c522cae">

2024-12-09 04:59 UTC, atomworks approved these changes
Looks ready to go, thank you!

2024-12-09 06:08 UTC, merged