Label props and prop refactor
future-standard/scorer-ui-kit pull request #530
Opened 2024-12-10 05:52 UTC by atomworks

This iteration was made to allow the labels for the back and share buttons to be overridden. Whilst doing this and adding to the story I realised we quickly began to overload the props we were sending and things were getting messy. This becomes more problematic, the deeper that components are nested. For this reason I decided to refactor this early while it is only being used in one project and we can limit the impact of breaking changes.

## How to Update to New Props
The following props have been removed and will need to be changed: `backLink`, `showShareLink` and `shareLink`

They have been replaced with two new object props: `back` and `share` which contain everything that is needed.

Instead of `backLink`, use:
```
back={
  link: '/example', // Same value as backLink
  label: 'Back' // Optional but intended for localisation overrides
}
```

```
share: {
  show: true, // default: true,
  
}
```

2024-12-17 03:05 UTC, isacoder requested changes
Hello Leonard,

Thanks for following up with this fix. The refactor breaking changes look necessary and I don't think there will be any issues with that.

I had to make some local updates to run this fix, so I'm not sure the result of the live review is fair. I see some issues with the passed "shared" label not been updated.

Please review the comments and let me know if you have any questions.

2024-12-18 03:02 UTC, atomworks commented
Thanks for the review @isacoder and apologies for it being in such a rough state, I'm not sure how I missed that string of problems when testing as it was certainly working when I did. Perhaps I made the error of a hasty last minute rename which didn't get the same attention.

I've just pushed some changes that should resolve all that. Considering the issue of defaults and how it was being handled, it felt like the best pattern in the end would be just to break down those components they could have there prop defaults managed at that level.

As a thought on that, and maybe this is just more of a note for me than anything, perhaps anytime we use an object in the future to pass through a set of props for something nested, that probably means the nested thing should be it's own component at some point. In the original PR, those things were part of the component, which is why it got a bit messy. It makes a lot more sense now.

2024-12-18 04:09 UTC, isacoder requested changes
Thanks for the update, everything is looking good and almost ready to merge.

However I discovered that I made a mistake in my comment about removing the $variables.

This is an scenario where they are necessary.
I was looking at the console while running the local version and noticed some warnings about props. Since the UtilityHeaderBack is using Link Component from the React Router Package the way props are defined is important. You can either follow their advice and have them to be lowercase or use $ at the beginning. That should remove the warning.

<img width="304" alt="Screenshot 2024-12-17 at 21 29 28" src="https://github.com/user-attachments/assets/220c1f1e-1754-4050-bd17-2e02773ef251" />

2024-12-20 02:53 UTC, atomworks commented
In the end, as it's a good indicator for a prop that's effecting a styled component (and so will have a visual impact, rather than just a data change), it's useful to see and doesn't create a weird contrast to all our other camel case props.

2024-12-21 01:17 UTC, isacoder approved these changes
Thanks for the refactor and polish of UtilityHeader. It's great to have this for the final release of the year!

2024-12-21 01:18 UTC, merged