WIP  Global UI named NavigationTemplate for now
future-standard/scorer-ui-kit pull request #74
Opened 2021-05-14 10:39 UTC by isacoder

### Requirements

[Bugherd#42](https://www.bugherd.com/projects/216308/kanban)
[Main Menu] Make responsive

1. Create a master component for the global UI pattern. As part of this it should fix the behaviour of how the main menu opens at different desktop sizes. (smaller sizes, menu overlays content. Larger size, menu pushes content.)
2. Adding the mobile menu as per designs in Zeplin (with placeholder notifications area at first)
3. Notifications systems properly implemented (including Toast :thumbsup:  notifications and also I’d like to add an option for the browser API notifications too)

Designs
Menu
https://zpl.io/VDJ6nOw
zpl://screen?sid=5ede1065786044b779f6d6ac&pid=5ee9f5a23a30524bf9e5b2a9

Notifications
https://zpl.io/aRJDPqp
zpl://screen?sid=5ede106614cfd8b6647c855e&pid=5ee9f5a23a30524bf9e5b2a9

User
https://zpl.io/ag4XNnA
zpl://screen?sid=5ede106633d356b94fa1ceb3&pid=5ee9f5a23a30524bf9e5b2a9

### Implementation

### Screenshoots

2021-05-26 09:01 UTC, atomworks requested changes
I've run through all the code and it's looking solid! Got a few comments (as always) to try and refine some things in code and in usability.

Biggest issue for me right now, we have the visual glitching issue when menus and submenus open and close for the first times. 😭  Is this just a caused by us now wrapping the content? How hard do you think it will be to eliminate this?

Also, how hard would it be to add some different dummy pages to the example (or even better, the story)? They don't need to be anything clever (page title component & different lipsum paragraphs maybe), just different enough to demonstrate the interactions working and how to use the wrapper itself with content. I have no real experience with React Router so if this isn't a job that's pretty quick and easy, let's not worry at the moment.

I have some other observations but I don't think anything worth sharing now. I think some of those might even be their own future tasks. 

Thanks for you hard work on this!

2021-05-26 10:10 UTC, isacoder commented on src/themes/common.tsx
>  };
First let me apologize for the typo I have in the first media query it should be 319
```
mobileS: `(max-width: 319px)`,
```

My biggest concern here was to get a way to have both values for JS and CSS.

I made a search about different options and my favorite was this one
[how-to-use-media-queries-with-styled-components](https://jsramblings.com/how-to-use-media-queries-with-styled-components/#:~:text=Media%20queries%20with%20styled%20components%20work%20the%20same%20as%20in,different%20device%20sizes%2C%20continue%20below.)

There are two mobiles becase I saw there was two mobile versions in the Zepplin with some small sizes variations

MobileS
https://zpl.io/2GJ6Omr

MobileM
https://zpl.io/ag4XNnA

About the naming  small, medium, large, xlarge and xxLarge works for me, I made them mainly based on the requirements document you shared, so I'll go ahead and make this update.

2021-05-27 07:47 UTC, isacoder commented on storybook/src/stories/Global/NavigationTemplate.stories.tsx
> +    <NavigationTemplate
updated!

2021-05-27 07:47 UTC, isacoder commented on src/hooks/useBreakpoints.ts
> +| 'desktopL';
updated!

2021-05-31 01:39 UTC, isacoder commented on src/Global/atoms/Layout.tsx
> +export const Content2 = styled.div`
Updated to ContentArea

2021-05-31 01:43 UTC, isacoder commented
I have updated all requested, added the pages to Storybook and removed the example page.
After the review of the Glich with Josh we agreed that this is something that currently lives in the base code.
We have not seen it much because current Apps does not have a lot of options in menus.

Therefore, we do need to fix this but perhaps we can add this PR and follow up this issue in another.

2021-06-01 08:39 UTC, atomworks approved these changes
Awesome. Thanks for those changes. Looks great.

2021-06-04 04:03 UTC, JoshLipps approved these changes
LGTM

2021-06-04 04:14 UTC, merged